version: "3.8"

services:
  # database
  db:
    container_name: mysql
    image: mysql:8.0.32
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Jakarta
    volumes:
      - "mysql:/var/lib/mysql"
    networks:
      - mysql
  # phpmyadmin
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.1-apache
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - TZ=Asia/Jakarta
    networks:
      - mysql

volumes:
  mysql:
    name: mysql

networks:
  mysql:
    name: mysql
    driver: bridge